config/routes.rb
Project::Application.routes.draw do
  resources :skippings

  resources :people

  resources :specialities

  resources :chairs

  resources :scientmen

  resources :aspirants

  resources :marks

  resources :subjects

   root :to => 'aspirants#index'

end

app/models/aspirant.rb
class Aspirant < ActiveRecord::Base
  belongs_to :person
  belongs_to :scientman
  belongs_to :speciality
  #has_many :marks
  has_many :skippings
  
  validates :aspirant_type,:presence=>true
  validates :start_study_date,:presence=>true
  validates :maybe_finish_date,:presence=>true
  
  #validates :scientman_id,:presence => true,:uniqueness => true
  
  accepts_nested_attributes_for :skippings, :allow_destroy => true
  
  before_save { 
    self.skip = skippings.inject(0) { |total, s| total + (s.finish - s.start) }
    self.maybe_finish_date = self.start_study_date + 3.years + self.skip.days
  }
  
  Type_asp=["Аспирант","Докторант","Соискатель"]
  Forma=["Очная, коммерческая","Очная, бюджетная","Заочная, коммерческое"]
  
  def asptype
	Type_asp[aspirant_type]
  end
  
  def studyform
    Forma[study_form]
  end
  
  def sex
    male ? 'мужской' : 'женский'
  end
    
end

app/controllers/aspirants_controller.rb
class AspirantsController < ApplicationController
  # GET /aspirants
  # GET /aspirants.json
  def index
    @aspirants = Aspirant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @aspirants }
    end
  end

  # GET /aspirants/1
  # GET /aspirants/1.json
  def show
    @aspirant = Aspirant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @aspirant }
    end
  end

  # GET /aspirants/new
  # GET /aspirants/new.json
  def new
    @aspirant = Aspirant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @aspirant }
    end
  end

  # GET /aspirants/1/edit
  def edit
    @aspirant = Aspirant.find(params[:id])
  end

  # POST /aspirants
  # POST /aspirants.json
  def create
    @aspirant = Aspirant.new(params[:aspirant])

    respond_to do |format|
      if @aspirant.save
        format.html { redirect_to @aspirant, :notice => 'Аспирант успешно создан.' }
        format.json { render :json => @aspirant, :status => :created, :location => @aspirant }
      else
        format.html { render :action => "new" }
        format.json { render :json => @aspirant.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /aspirants/1
  # PUT /aspirants/1.json
  def update
    @aspirant = Aspirant.find(params[:id])

    respond_to do |format|
      if @aspirant.update_attributes(params[:aspirant])
        format.html { redirect_to @aspirant, :notice => 'Аспирант успешно изменен.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @aspirant.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /aspirants/1
  # DELETE /aspirants/1.json
  def destroy
    @aspirant = Aspirant.find(params[:id])
    @aspirant.destroy

    respond_to do |format|
      format.html { redirect_to aspirants_url }
      format.json { head :ok }
    end
  end
end

app/helpers/aspirants_helper.rb
module AspirantsHelper

def scientman_name_for(aspirant)
	if aspirant.scientman
		aspirant.scientman.person.full_name
		else
		"Не назначено"
	end
end	

end

app/views/aspirants/_form.html.erb
<%= form_for(@aspirant) do |f| %>
  <% if @aspirant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aspirant.errors.count, "error") %> prohibited this aspirant from being saved:</h2>

      <ul>
      <% @aspirant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :person_id %><br />
    <%= f.select :person_id, Person.where(:status => 2).map{ |s| [s.full_name, s.id]} %>
  </div>
  <!--
  <div class="actions">
	<%= f.fields_for :person do |builder| %>
		<%= render "person_fields", :f => builder, :person => (@aspirant.person || Person.new) %>
	<% end %>
  </div>
  -->
  <div class="field">
    <%= f.label :aspirant_type %><br />
    <%= f.select :aspirant_type, options_for_select([["Аспирант", 0], ["Докторант", 1], ["Соискатель",2]], @aspirant.aspirant_type) %>
  </div>
  <div class="field">
    <%= f.label :start_study_date %><br />
    <%= f.date_select :start_study_date %>
  </div>
  <div class="field">
    <%= f.label :maybe_finish_date %><br />
    <%= f.date_select :maybe_finish_date %>
  </div>
  <div class="field">
    <%= f.label :finish_study_date %><br />
    <%= f.date_select :finish_study_date, :end_year => Time.now.year+15 %>
  </div>
  <div class="field">
    <%= f.label :scientman_id %><br />
    <%= f.select :scientman_id, [["Не назначен", ""]] + Scientman.all.map{ |s| [s.person.full_name, s.id]}, :selected => "" %>
  </div>
  <div class="field">
    <%= f.label :scientman_day %><br />
    <%= f.date_select :scientman_day %>
  </div>
  <div class="field">
    <%= f.label :study_form %><br />
    <%= f.select :study_form, options_for_select([["Очная, коммерческая", 0], ["Очная, бюджетная", 1], ["Заочная, коммерческое",2]], @aspirant.study_form) %>
  </div>
  <div class="field">
    <%= f.label :protect_status %><br />
    <%= f.check_box :protect_status %>
  </div>
  <div class="field">
    <%= f.label :work_title %><br />
    <%= f.text_field :work_title %>
  </div>
  <div class="field">
    <%= f.label :protect_data %><br />
    <%= f.date_select :protect_data %>
  </div>
  <div class="field">
    <%= f.label :payment %><br />
    <%= f.check_box :payment %>
  </div>
  <div class="field">
    <%= f.label :speciality_id %><br />
    <%= f.select :speciality_id, Speciality.all.map{ |s| [s.name, s.id]} %>
  </div>
  <p><%= link_to_add_fields "Добавить пропуск", f, :skippings %></p>
  <%= f.fields_for :skippings do |builder| %>
    <%= render "skipping_fields", :f => builder %>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aspirants/_person_fields.html.erb
<div class="field">
    <%= f.label :second_name %><br />
    <%= f.text_field :second_name %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br />
    <%= f.date_select :birthday, :start_year => Time.now.year - 200, :end_year => Time.now.year, :default => 23.years.ago %>
  </div>
  <div class="field">
    <%= f.label :telephone %><br />
    <%= f.text_field :telephone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :male %><br />
    <%= f.radio_button :male,"1",:checked=> person.male? %>
    "Мужской"
    <br/>
    <%= f.radio_button :male,"0",:checked=> !person.male? %>
    "Женский"
    <br/>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.select :status, options_for_select([["Неопределен", 0], ["Науч. руководитель", 1], ["Аспирант",2]], person.status) %>
  </div>

app/views/aspirants/_skipping_fields.html.erb
<div class="fields">
<div class="field">
  <%= f.label :start %><br />
  <%= f.date_select :start %>
</div>
<div class="field">
  <%= f.label :finish %><br />
  <%= f.date_select :finish %>
</div>
<%= link_to_remove_fields "Удалить", f %>
</div>

app/views/aspirants/edit.html.erb
<h1>Редактирование аспранта</h1>

<%= render 'form' %>

<%= link_to 'Показать', @aspirant %> |
<%= link_to 'Назад к списку аспирантов', aspirants_path %>

app/views/aspirants/index.html.erb
<h1>Список аспирантов</h1>

<table>
  <tr>
    <th>Аспирант</th>
    <th>Тип аспиранта</th>
    <th>Начало обучения</th>
    <th>Предположительное окончание обучения</th>
    <th>Окончание обучения</th>
    <th>Научный руководитель</th>
    <th>Форма обучения</th>
    <th>Статус защиты</th>
    <th>Дата защиты</th>
    <th>Оплата текущего семестра</th>
    <th>Специальность</th>
    <th>Всего пропущено</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @aspirants.each do |aspirant| %>
  <tr>
    <td><%= link_to aspirant.person.full_name, aspirant %></td>
    <td><%= aspirant.asptype %></td>
    <td><%= aspirant.start_study_date.strftime("%d.%m.%Y") %></td>
    <td><%= aspirant.maybe_finish_date.strftime("%d.%m.%Y") %></td>
    <td><%= aspirant.finish_study_date.strftime("%d.%m.%Y") %></td>
    <td><%= scientman_name_for(aspirant) %></td>
    <td><%= aspirant.studyform %></td>
    <td><%= aspirant.protect_status %></td>
    <td><%= aspirant.protect_data.strftime("%d.%m.%Y") %></td>
    <td><% if aspirant.payment %>
			<%= "Оплачено" %>
			<% else %>
			<%= "Задолженность" %>
		<% end %>
    <td><%= aspirant.speciality.name %></td>
    <td><%= aspirant.skip %></td>
    <td><%= link_to 'Изменить', edit_aspirant_path(aspirant) %></td>
    <td><%= link_to 'Удалить', aspirant, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Новый аспирант', new_aspirant_path %>

app/views/aspirants/new.html.erb
<h1>Новый аспирант</h1>

<%= render 'form' %>

<%= link_to 'Назад к списку аспирантов', aspirants_path %>

app/views/aspirants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%=Aspirant.human_attribute_name(:person_id)%>:</b>
  <%= @aspirant.person.full_name %>
</p>

<p>
  <b><%=Aspirant.human_attribute_name(:aspirant_type)%>:</b>
  <%= @aspirant.asptype %>
</p>

<p>
  <b><%=Aspirant.human_attribute_name(:start_study_date)%>:</b>
  <%= @aspirant.start_study_date.strftime("%d.%m.%Y") %>
</p>

<p>
  <b><%=Aspirant.human_attribute_name(:maybe_finish_date)%>:</b>
  <%= @aspirant.maybe_finish_date.strftime("%d.%m.%Y") %>
</p>

<p>
  <b><%=Aspirant.human_attribute_name(:finish_study_date)%>:</b>
  <%= @aspirant.finish_study_date.strftime("%d.%m.%Y") %>
</p>

<p>
  <b><%=Aspirant.human_attribute_name(:scientman_id)%>:</b>
  <%= scientman_name_for(@aspirant) %>
</p>

<p>
  <b><%=Aspirant.human_attribute_name(:scientman_day)%>:</b>
  <%= @aspirant.scientman_day.strftime("%d.%m.%Y") %>
</p>

<p>
  <b><%=Aspirant.human_attribute_name(:study_form)%>:</b>
  <%= @aspirant.studyform %>
</p>

<p>
  <b><%=Aspirant.human_attribute_name(:protect_status)%>:</b>
  <%= @aspirant.protect_status %>
</p>

<p>
  <b><%=Aspirant.human_attribute_name(:work_title)%>:</b>
  <%= @aspirant.work_title %>
</p>

<p>
  <b><%=Aspirant.human_attribute_name(:protect_data)%>:</b>
  <%= @aspirant.protect_data.strftime("%d.%m.%Y") %>
</p>

<p>
  <b><%=Aspirant.human_attribute_name(:payment)%>:</b>
  <% if @aspirant.payment %>
      <%= "Оплачено" %>
	<% else %>
	  <%= "Задолженность" %>
  <% end %>
</p>

<p>
  <b><%=Aspirant.human_attribute_name(:specialiti_id)%>:</b>
  <%= @aspirant.speciality.name %>
</p>

<p>
  <b><%=Aspirant.human_attribute_name(:skip)%>:</b>
  <%= @aspirant.skip %> дней
  <br>
  <% @aspirant.skippings.each do |s| %>
    <%= s.start %> -- <%= s.finish %> <br>
  <% end %>
</p>

<table>
	<thead>
		<tr><th colspan="3">Вступительный экзамен</th>
		<tr><th>Предмет</th><th>Оценка</th><th>Дата сдачи</th>
		
	</thead>
	<tbody>
		<% @aspirant.marks.where(:value_type => 1).each do |mark| %>
		<tr><td><%= mark.subject.name %></td><td><%= mark.value %></td><td><%= mark.day_exam %></td>
		<% end %>
	</tbody>
</table>
<table>
	<thead>
		<tr><th colspan="3">Кандидатский минимум</th>
		<tr><th>Предмет</th><th>Оценка</th><th>Дата сдачи</th>
	</thead>
	<tbody>
		<% @aspirant.marks.where(:value_type => 2).each do |mark| %>
		<tr><td><%= mark.subject.name %></td><td><%= mark.value %></td><td><%= mark.day_exam %></td>
		<% end %>
	</tbody>
</table>

<%= link_to 'Изменить', edit_aspirant_path(@aspirant) %> |
<%= link_to 'Назад к списку аспирантов', aspirants_path %>