config/routes.rb
Project::Application.routes.draw do
  resources :skippings

  resources :people

  resources :specialities

  resources :chairs

  resources :scientmen

  resources :aspirants

  resources :marks

  resources :subjects

   root :to => 'aspirants#index'

end

app/models/speciality.rb
class Speciality < ActiveRecord::Base
  has_and_belongs_to_many :subjects
  belongs_to :chair
  has_many :aspirants
  
  validates :name, :presence => true
  validates :key_specialiti,:presence => true,:uniqueness => true
   
end

app/controllers/specialities_controller.rb
class SpecialitiesController < ApplicationController
  # GET /specialities
  # GET /specialities.json
  def index
    @specialities = Speciality.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @specialities }
    end
  end

  # GET /specialities/1
  # GET /specialities/1.json
  def show
    @speciality = Speciality.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @speciality }
    end
  end

  # GET /specialities/new
  # GET /specialities/new.json
  def new
    @speciality = Speciality.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @speciality }
    end
  end

  # GET /specialities/1/edit
  def edit
    @speciality = Speciality.find(params[:id])
  end

  # POST /specialities
  # POST /specialities.json
  def create
    @speciality = Speciality.new(params[:speciality])

    respond_to do |format|
      if @speciality.save
        format.html { redirect_to @speciality, :notice => 'Специальность создана.' }
        format.json { render :json => @speciality, :status => :created, :location => @speciality }
      else
        format.html { render :action => "new" }
        format.json { render :json => @speciality.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /specialities/1
  # PUT /specialities/1.json
  def update
    @speciality = Speciality.find(params[:id])

    respond_to do |format|
      if @speciality.update_attributes(params[:speciality])
        format.html { redirect_to @speciality, :notice => 'SСпециальность изменена.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @speciality.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /specialities/1
  # DELETE /specialities/1.json
  def destroy
    @speciality = Speciality.find(params[:id])
    @speciality.destroy

    respond_to do |format|
      format.html { redirect_to specialities_url }
      format.json { head :ok }
    end
  end
end

app/helpers/specialities_helper.rb
module SpecialitiesHelper
end

app/views/specialities/_form.html.erb
<%= form_for(@speciality) do |f| %>
  <% if @speciality.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@speciality.errors.count, "error") %> prohibited this speciality from being saved:</h2>

      <ul>
      <% @speciality.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :key_specialiti %><br />
    <%= f.text_field :key_specialiti %>
  </div>
  <div class="field">
   <%= f.label :chair_id %><br />
   <%= f.select :chair_id, Chair.all.map{ |s| [s.name, s.id]} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/specialities/edit.html.erb
<h1>Редактирование специальности</h1>

<%= render 'form' %>

<%= link_to 'Показать', @speciality %> |
<%= link_to 'Назад', specialities_path %>

app/views/specialities/index.html.erb
<h1>Список специальностей</h1>

<table>
  <tr>
    <th>Название</th>
    <th>Код специальности</th>
    <th>Кафедра</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @specialities.each do |speciality| %>
  <tr>
    <td><%= speciality.name %></td>
    <td><%= speciality.key_specialiti %></td>
    <td><%= link_to speciality.chair.name, chair_path(speciality.chair) %></td>
    <td><%= link_to 'Показать', speciality %></td>
    <td><%= link_to 'Изменить', edit_speciality_path(speciality) %></td>
    <td><%= link_to 'Удалить', speciality, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Новая специальность', new_speciality_path %>

app/views/specialities/new.html.erb
<h1>Новая специальность</h1>

<%= render 'form' %>

<%= link_to 'Назад', specialities_path %>

app/views/specialities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%=Speciality.human_attribute_name(:name)%>:</b>
  <%= @speciality.name %>
</p>
<p>
  <b><%=Speciality.human_attribute_name(:key_specialiti)%>:</b>
  <%= @speciality.key_specialiti %>
</p>
<p>
  <b><%=Speciality.human_attribute_name(:chair_id)%>:</b>
  <%= @speciality.chair.name %>
</p>


<%= link_to 'Редактировать', edit_speciality_path(@speciality) %> |
<%= link_to 'Назад', specialities_path %>