config/routes.rb
Project::Application.routes.draw do
  resources :skippings

  resources :people

  resources :specialities

  resources :chairs

  resources :scientmen

  resources :aspirants

  resources :marks

  resources :subjects

   root :to => 'aspirants#index'

end

app/views/layouts/_aside.haml
#aside.box
  .padding.box
    %p#logo= link_to image_tag("logo.png", :alt=>"Видео каталог"), root_path
  %ul.box
    -Genre.all.each do |genre|
      %li{:id=>genre==@current_genre ? "submenu-active" : nil}=link_to genre.name,genre

app/views/layouts/_footer.haml
#footer.box
  %p.f-left
    &copy;
    Система Учета Аспирантов, МГИУ, 2012г.

app/views/layouts/_menu.haml
#menu.box
  %ul.box
    %li{:id=>controller_name=='people' ? "menu-active" : nil}=link_to content_tag(:span,"Люди"),people_path
    %li{:id=>controller_name=='specialities' ? "menu-active" : nil}=link_to content_tag(:span,"Специальности"),specialities_path
    %li{:id=>controller_name=='chairs' ? "menu-active" : nil}=link_to content_tag(:span,"Кафедры"),chairs_path
    %li{:id=>controller_name=='scientmen' ? "menu-active" : nil}=link_to content_tag(:span,"Научные руководители"),scientmen_path
    %li{:id=>controller_name=='aspirants' ? "menu-active" : nil}=link_to content_tag(:span,"Аспиранты"),aspirants_path
    %li{:id=>controller_name=='marks' ? "menu-active" : nil}=link_to content_tag(:span, "Оценки"),marks_path
    %li{:id=>controller_name=='subjects' ? "menu-active" : nil}=link_to content_tag(:span, "Предметы"),subjects_path

app/views/layouts/_tray.haml
#tray.box

app/views/layouts/application.haml
!!!
%html
  %head
    %title Система учета аспирантов
    = stylesheet_link_tag 'reset', 'main', '2col', 'style', 'mystyle','token-input-facebook'
    /[if lte IE 6]
      =stylesheet_link_tag 'main-ie6'
    =javascript_include_tag :'application','jquery.tokeninput'
    = csrf_meta_tag
  %body
    #main
      = render 'layouts/tray'
      %hr.noscreen
      = render 'layouts/menu'
      = yield      
      = render 'layouts/footer'
      

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <li><%= link_to "Люди", people_path %></li>
  <li><%= link_to "Специальности", specialities_path %></li>
  <li><%= link_to "Кафедры", chairs_path %></li>
  <li><%= link_to "Научные руководители", scientmen_path %></li>
  <li><%= link_to "Аспиранты", aspirants_path %></li>
  <li><%= link_to "Оценки", marks_path %></li>
  <li><%= link_to "Предметы", subjects_path %></li>
<%= yield %>

</body>
</html>